'use strict';

var segmentBuilder = require('../../modules/segmentation/segment_builder');
var analyzerPostprocess = require('../../modules/postprocess/analyzer_postprocess');
var continuityEnforcer = require('./continuity_enforcer');

function runPostprocessStage(ctx) {
    ctx = ctx || {};

    var params = ctx.params || {};
    var trackInfos = ctx.trackInfos || [];
    var trackCount = trackInfos.length;
    var rmsProfiles = ctx.rmsProfiles || [];
    var rawRmsProfiles = ctx.rawRmsProfiles || [];
    var vadResults = ctx.vadResults || [];
    var laughterResults = ctx.laughterResults || [];
    var totalDurationSec = ctx.totalDurationSec || 0;
    var progress = ctx.progress || function () { };
    var resolvedSegments = ctx.resolvedSegments || [];
    var i;

    // --- NEW: Strict post-processing to eliminate tiny segments generated by overlap resolver
    progress(75, 'Enforcing minimum segment duration...');

    var postMinMs = (params.postOverlapMinSegmentMs !== undefined)
        ? params.postOverlapMinSegmentMs
        : Math.max(80, Math.round(params.minSegmentMs * 0.6));
    resolvedSegments = analyzerPostprocess.enforceMinimumSegmentDuration(resolvedSegments, postMinMs / 1000);
    // --- END NEW

    if (params.enableLowSignificancePrune) {
        // Pass 1 (conservative): prune obvious weak artifacts before gap filling.
        resolvedSegments = analyzerPostprocess.pruneLowSignificanceSegments(resolvedSegments, rmsProfiles, vadResults, {
            frameDurationMs: params.frameDurationMs,
            maxDurationMs: Math.max(400, Math.round(params.lowSignificanceMaxDurationMs * 0.7)),
            minPeakAboveThresholdDb: Math.max(0.5, params.lowSignificanceMinPeakAboveThresholdDb - 1.0),
            minMeanAboveThresholdDb: params.lowSignificanceMinMeanAboveThresholdDb - 0.5,
            protectLaughter: params.protectLaughterInPostprocess,
            laughterResults: laughterResults,
            laughterProtectMinConfidence: params.laughterPostprocessProtectMinConfidence,
            laughterProtectMinCoverage: params.laughterPostprocessProtectMinCoverage
        }, trackInfos, 'pre');
    }

    if (params.enablePreTriggerCleanup) {
        resolvedSegments = analyzerPostprocess.cleanupWeakPreTriggers(resolvedSegments, rmsProfiles, vadResults, {
            frameDurationMs: params.frameDurationMs,
            maxDurationMs: params.preTriggerMaxDurationMs,
            joinGapMs: params.preTriggerJoinGapMs,
            minPeakDeltaDb: params.preTriggerMinPeakDeltaDb,
            absorbGapMs: params.preTriggerAbsorbGapMs,
            protectLaughter: params.protectLaughterInPostprocess,
            laughterResults: laughterResults,
            laughterProtectMinConfidence: params.laughterPostprocessProtectMinConfidence,
            laughterProtectMinCoverage: params.laughterPostprocessProtectMinCoverage
        }, trackInfos);
    }

    if (params.independentTrackAnalysis && params.enablePrimaryTrackGapFill) {
        resolvedSegments = analyzerPostprocess.applyPrimaryTrackGapFill(resolvedSegments, rmsProfiles, {
            frameDurationMs: params.frameDurationMs,
            maxGapMs: params.primaryTrackGapFillMaxMs,
            quietDb: params.primaryTrackGapFillQuietDb
        });
    }



    if (params.enableDominantTrackStickiness) {
        resolvedSegments = analyzerPostprocess.applyDominantTrackStickiness(resolvedSegments, rmsProfiles, {
            frameDurationMs: params.frameDurationMs,
            holdMs: params.dominantTrackHoldMs,
            returnWindowMs: params.dominantTrackReturnWindowMs
        }, trackInfos);
    }

    if (params.independentTrackAnalysis && params.enableCrossTrackHandoverSmoothing) {
        resolvedSegments = analyzerPostprocess.smoothCrossTrackHandovers(resolvedSegments, rmsProfiles, vadResults, {
            frameDurationMs: params.frameDurationMs,
            maxStartDelayMs: params.handoverMaxStartDelayMs,
            leadMs: params.handoverLeadMs,
            weakOnsetProbeMs: params.handoverWeakOnsetProbeMs,
            maxWeakOverlapLeadMs: params.handoverMaxWeakOverlapLeadMs,
            onsetPeakMinDb: params.handoverOnsetPeakMinDb,
            onsetMeanMinDb: params.handoverOnsetMeanMinDb,
            minSegmentMs: params.handoverMinSegmentMs
        }, trackInfos);
    } else {
        for (i = 0; i < trackCount; i++) {
            if (trackInfos[i]) trackInfos[i].handoverStartDelayedMs = 0;
        }
    }

    if (params.enableLowSignificancePrune) {
        // Pass 2 (strict): clean up weak snippets that still survive after continuity fill.
        resolvedSegments = analyzerPostprocess.pruneLowSignificanceSegments(resolvedSegments, rmsProfiles, vadResults, {
            frameDurationMs: params.frameDurationMs,
            maxDurationMs: params.lowSignificanceMaxDurationMs,
            minPeakAboveThresholdDb: params.lowSignificanceMinPeakAboveThresholdDb,
            minMeanAboveThresholdDb: params.lowSignificanceMinMeanAboveThresholdDb,
            protectLaughter: params.protectLaughterInPostprocess,
            laughterResults: laughterResults,
            laughterProtectMinConfidence: params.laughterPostprocessProtectMinConfidence,
            laughterProtectMinCoverage: params.laughterPostprocessProtectMinCoverage
        }, trackInfos, 'post');
    }

    if (params.enablePeakAnchorKeep) {
        resolvedSegments = analyzerPostprocess.reinforceHighPeakAnchors(resolvedSegments, rmsProfiles, vadResults, {
            frameDurationMs: params.frameDurationMs,
            minDbAboveThreshold: params.peakAnchorMinDbAboveThreshold,
            prePadMs: params.peakAnchorPrePadMs,
            postPadMs: params.peakAnchorPostPadMs,
            minClusterMs: params.peakAnchorMinClusterMs,
            joinGapMs: params.peakAnchorJoinGapMs
        }, trackInfos, totalDurationSec);
    }

    // Final conservative cleanup: remove only clearly weak, isolated residual snippets.
    // Guardrails:
    // - no global threshold shifts
    // - no dominance/fillGaps side effects (disabled when fillGaps=true)
    // - protect short turn-taking and boundary continuity
    if (params.enableResidualSnippetPrune && !params.fillGaps) {
        resolvedSegments = analyzerPostprocess.pruneResidualSnippets(resolvedSegments, rmsProfiles, rawRmsProfiles, vadResults, {
            frameDurationMs: params.frameDurationMs,
            maxDurationMs: params.residualSnippetMaxDurationMs,
            minPeakAboveThresholdDb: params.residualSnippetMinPeakAboveThresholdDb,
            minMeanAboveThresholdDb: params.residualSnippetMinMeanAboveThresholdDb,
            maxPeakDbFs: params.residualSnippetMaxPeakDbFs,
            maxMeanDbFs: params.residualSnippetMaxMeanDbFs,
            protectGapMs: params.residualSnippetProtectGapMs,
            protectOtherOverlapRatio: params.residualSnippetProtectOtherOverlapRatio,
            protectLaughter: params.protectLaughterInPostprocess,
            laughterResults: laughterResults,
            laughterProtectMinConfidence: params.laughterPostprocessProtectMinConfidence,
            laughterProtectMinCoverage: params.laughterPostprocessProtectMinCoverage
        }, trackInfos);
    }

    // Final hard floor in absolute dBFS for active segments.
    // This is intentionally last so earlier context-aware passes can run first.
    if (params.enableFinalPeakGate && !params.fillGaps) {
        resolvedSegments = analyzerPostprocess.filterByAbsolutePeakFloor(resolvedSegments, rawRmsProfiles, {
            frameDurationMs: params.frameDurationMs,
            minPeakDbFs: params.finalMinPeakDbFs,
            protectLaughter: params.protectLaughterInPostprocess,
            laughterResults: laughterResults,
            laughterProtectMinConfidence: params.laughterPostprocessProtectMinConfidence,
            laughterProtectMinCoverage: params.laughterPostprocessProtectMinCoverage
        }, trackInfos);
    }

    // Re-apply handover smoothing after anchor/final cleanup passes because
    // those passes can re-introduce overly early cross-track starts.
    if (params.independentTrackAnalysis && params.enableCrossTrackHandoverSmoothing) {
        resolvedSegments = analyzerPostprocess.smoothCrossTrackHandovers(resolvedSegments, rmsProfiles, vadResults, {
            frameDurationMs: params.frameDurationMs,
            maxStartDelayMs: params.handoverMaxStartDelayMs,
            leadMs: params.handoverLeadMs,
            weakOnsetProbeMs: params.handoverWeakOnsetProbeMs,
            maxWeakOverlapLeadMs: params.handoverMaxWeakOverlapLeadMs,
            onsetPeakMinDb: params.handoverOnsetPeakMinDb,
            onsetMeanMinDb: params.handoverOnsetMeanMinDb,
            minSegmentMs: params.handoverMinSegmentMs
        }, trackInfos);
    }

    // Final safety net: ensure at least one dominant speaker track remains active
    // even after late postprocess passes potentially created global silent gaps.
    if (params.enforceAlwaysOneTrackOpen) {
        var finalAlwaysOpen = continuityEnforcer.enforceAlwaysOneTrackOnResolvedSegments(resolvedSegments, rmsProfiles, {
            frameDurationMs: params.frameDurationMs,
            dominanceWindowMs: params.alwaysOpenDominanceWindowMs,
            stickinessDb: params.alwaysOpenStickinessDb
        });
        resolvedSegments = finalAlwaysOpen.resolvedSegments;

        for (i = 0; i < trackCount; i++) {
            if (trackInfos[i]) {
                trackInfos[i].alwaysOpenFilledFramesPost = finalAlwaysOpen.perTrackFilledFrames[i] || 0;
            }
        }
    } else {
        for (i = 0; i < trackCount; i++) {
            if (trackInfos[i]) trackInfos[i].alwaysOpenFilledFramesPost = 0;
        }
    }

    for (i = 0; i < trackCount; i++) {
        var finalStats = computeStatsFromResolvedSegments(resolvedSegments[i], totalDurationSec);
        trackInfos[i].segmentCount = finalStats.segmentCount;
        trackInfos[i].activePercent = finalStats.activePercent;
        trackInfos[i].totalActiveSec = finalStats.totalActiveSec;
    }

    return {
        resolvedSegments: resolvedSegments
    };
}

function computeStatsFromResolvedSegments(trackSegments, totalDurationSec) {
    var active = [];
    for (var i = 0; i < (trackSegments || []).length; i++) {
        if (trackSegments[i].state !== 'suppressed') active.push(trackSegments[i]);
    }
    return segmentBuilder.computeStats(active, totalDurationSec);
}

module.exports = {
    runPostprocessStage: runPostprocessStage
};
